# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/masaüstü/yazılımileilgilihersey/onluk/amazonton11/anasayfa.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(677, 594)
        self.baslat = QtWidgets.QPushButton(Widget)
        self.baslat.setGeometry(QtCore.QRect(270, 520, 131, 51))
        self.baslat.setObjectName("baslat")
        self.katsayi = QtWidgets.QLineEdit(Widget)
        self.katsayi.setGeometry(QtCore.QRect(370, 180, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.katsayi.setFont(font)
        self.katsayi.setObjectName("katsayi")
        self.dosya_yukle_label = QtWidgets.QLabel(Widget)
        self.dosya_yukle_label.setGeometry(QtCore.QRect(10, 80, 551, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.dosya_yukle_label.setFont(font)
        self.dosya_yukle_label.setObjectName("dosya_yukle_label")
        self.kupon_id_label = QtWidgets.QLabel(Widget)
        self.kupon_id_label.setGeometry(QtCore.QRect(0, 130, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kupon_id_label.setFont(font)
        self.kupon_id_label.setObjectName("kupon_id_label")
        self.dosya_yukle = QtWidgets.QPushButton(Widget)
        self.dosya_yukle.setGeometry(QtCore.QRect(200, 10, 131, 51))
        self.dosya_yukle.setObjectName("dosya_yukle")
        self.line = QtWidgets.QFrame(Widget)
        self.line.setGeometry(QtCore.QRect(0, 120, 681, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.kupon_id_label_2 = QtWidgets.QLabel(Widget)
        self.kupon_id_label_2.setGeometry(QtCore.QRect(180, 130, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kupon_id_label_2.setFont(font)
        self.kupon_id_label_2.setObjectName("kupon_id_label_2")
        self.kupon_id_label_3 = QtWidgets.QLabel(Widget)
        self.kupon_id_label_3.setGeometry(QtCore.QRect(400, 130, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kupon_id_label_3.setFont(font)
        self.kupon_id_label_3.setObjectName("kupon_id_label_3")
        self.excell = QtWidgets.QCheckBox(Widget)
        self.excell.setGeometry(QtCore.QRect(0, 180, 121, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.excell.setFont(font)
        self.excell.setObjectName("excell")
        self.xml = QtWidgets.QCheckBox(Widget)
        self.xml.setGeometry(QtCore.QRect(0, 210, 121, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.xml.setFont(font)
        self.xml.setObjectName("xml")
        self.usd = QtWidgets.QCheckBox(Widget)
        self.usd.setGeometry(QtCore.QRect(190, 180, 121, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.usd.setFont(font)
        self.usd.setObjectName("usd")
        self.tl = QtWidgets.QCheckBox(Widget)
        self.tl.setGeometry(QtCore.QRect(190, 210, 121, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tl.setFont(font)
        self.tl.setObjectName("tl")
        self.line_2 = QtWidgets.QFrame(Widget)
        self.line_2.setGeometry(QtCore.QRect(0, 320, 771, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Widget)
        self.line_3.setGeometry(QtCore.QRect(-10, 500, 711, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.kapat = QtWidgets.QCheckBox(Widget)
        self.kapat.setGeometry(QtCore.QRect(10, 400, 211, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.kapat.setFont(font)
        self.kapat.setObjectName("kapat")
        self.baslik = QtWidgets.QCheckBox(Widget)
        self.baslik.setGeometry(QtCore.QRect(10, 370, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.baslik.setFont(font)
        self.baslik.setObjectName("baslik")
        self.resim = QtWidgets.QCheckBox(Widget)
        self.resim.setGeometry(QtCore.QRect(10, 430, 171, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.resim.setFont(font)
        self.resim.setObjectName("resim")
        self.fiyat = QtWidgets.QCheckBox(Widget)
        self.fiyat.setGeometry(QtCore.QRect(10, 340, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fiyat.setFont(font)
        self.fiyat.setObjectName("fiyat")
        self.line_4 = QtWidgets.QFrame(Widget)
        self.line_4.setGeometry(QtCore.QRect(163, 130, 20, 201))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Widget)
        self.line_5.setGeometry(QtCore.QRect(330, 130, 20, 201))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(Widget)
        self.line_6.setGeometry(QtCore.QRect(670, 0, 20, 601))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gun = QtWidgets.QLineEdit(Widget)
        self.gun.setGeometry(QtCore.QRect(270, 390, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.gun.setFont(font)
        self.gun.setObjectName("gun")
        self.kupon_id_label_4 = QtWidgets.QLabel(Widget)
        self.kupon_id_label_4.setGeometry(QtCore.QRect(290, 340, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kupon_id_label_4.setFont(font)
        self.kupon_id_label_4.setObjectName("kupon_id_label_4")
        self.hafta = QtWidgets.QLineEdit(Widget)
        self.hafta.setGeometry(QtCore.QRect(380, 390, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.hafta.setFont(font)
        self.hafta.setObjectName("hafta")
        self.kupon_id_label_5 = QtWidgets.QLabel(Widget)
        self.kupon_id_label_5.setGeometry(QtCore.QRect(390, 340, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kupon_id_label_5.setFont(font)
        self.kupon_id_label_5.setObjectName("kupon_id_label_5")
        self.ay = QtWidgets.QLineEdit(Widget)
        self.ay.setGeometry(QtCore.QRect(490, 390, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ay.setFont(font)
        self.ay.setObjectName("ay")
        self.kupon_id_label_6 = QtWidgets.QLabel(Widget)
        self.kupon_id_label_6.setGeometry(QtCore.QRect(510, 340, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kupon_id_label_6.setFont(font)
        self.kupon_id_label_6.setObjectName("kupon_id_label_6")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.baslat.setText(_translate("Widget", "Güncelle"))
        self.dosya_yukle_label.setText(_translate("Widget", "                                    Dosya Yüklenmedi"))
        self.kupon_id_label.setText(_translate("Widget", "Dosya Tipi"))
        self.dosya_yukle.setText(_translate("Widget", "Dosya Yukle"))
        self.kupon_id_label_2.setText(_translate("Widget", "Para Birimi"))
        self.kupon_id_label_3.setText(_translate("Widget", "Katsayı"))
        self.excell.setText(_translate("Widget", "Excel"))
        self.xml.setText(_translate("Widget", "XML"))
        self.usd.setText(_translate("Widget", "USD"))
        self.tl.setText(_translate("Widget", "TRY"))
        self.kapat.setText(_translate("Widget", "İşlem Bitince Kapat"))
        self.baslik.setText(_translate("Widget", "Başlık Güncelle"))
        self.resim.setText(_translate("Widget", "Resim Güncelle"))
        self.fiyat.setText(_translate("Widget", "Fiyat Güncelle"))
        self.kupon_id_label_4.setText(_translate("Widget", "Gun"))
        self.kupon_id_label_5.setText(_translate("Widget", "Hafta"))
        self.kupon_id_label_6.setText(_translate("Widget", "Ay"))

