# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/masaüstü/yazılımileilgilihersey/onluk/amazonton11/anasayfa.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(765, 512)
        self.baslat = QtWidgets.QPushButton(Widget)
        self.baslat.setGeometry(QtCore.QRect(50, 170, 131, 51))
        self.baslat.setObjectName("baslat")
        self.katsayi = QtWidgets.QLineEdit(Widget)
        self.katsayi.setGeometry(QtCore.QRect(360, 130, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.katsayi.setFont(font)
        self.katsayi.setObjectName("katsayi")
        self.dosya_yukle_label = QtWidgets.QLabel(Widget)
        self.dosya_yukle_label.setGeometry(QtCore.QRect(50, 130, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.dosya_yukle_label.setFont(font)
        self.dosya_yukle_label.setObjectName("dosya_yukle_label")
        self.kupon_id_label = QtWidgets.QLabel(Widget)
        self.kupon_id_label.setGeometry(QtCore.QRect(570, 50, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kupon_id_label.setFont(font)
        self.kupon_id_label.setObjectName("kupon_id_label")
        self.dosya_yukle = QtWidgets.QPushButton(Widget)
        self.dosya_yukle.setGeometry(QtCore.QRect(50, 70, 131, 51))
        self.dosya_yukle.setObjectName("dosya_yukle")
        self.line = QtWidgets.QFrame(Widget)
        self.line.setGeometry(QtCore.QRect(0, 50, 761, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.kupon_id_label_3 = QtWidgets.QLabel(Widget)
        self.kupon_id_label_3.setGeometry(QtCore.QRect(360, 80, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kupon_id_label_3.setFont(font)
        self.kupon_id_label_3.setObjectName("kupon_id_label_3")
        self.usd = QtWidgets.QCheckBox(Widget)
        self.usd.setGeometry(QtCore.QRect(570, 100, 121, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.usd.setFont(font)
        self.usd.setChecked(True)
        self.usd.setObjectName("usd")
        self.xml = QtWidgets.QCheckBox(Widget)
        self.xml.setGeometry(QtCore.QRect(570, 160, 121, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.xml.setFont(font)
        self.xml.setChecked(True)
        self.xml.setObjectName("xml")
        self.line_2 = QtWidgets.QFrame(Widget)
        self.line_2.setGeometry(QtCore.QRect(0, 500, 761, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.kapat = QtWidgets.QCheckBox(Widget)
        self.kapat.setGeometry(QtCore.QRect(300, 470, 211, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.kapat.setFont(font)
        self.kapat.setObjectName("kapat")
        self.line_4 = QtWidgets.QFrame(Widget)
        self.line_4.setGeometry(QtCore.QRect(250, 60, 20, 401))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_6 = QtWidgets.QFrame(Widget)
        self.line_6.setGeometry(QtCore.QRect(750, 0, 20, 511))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gun = QtWidgets.QLineEdit(Widget)
        self.gun.setGeometry(QtCore.QRect(350, 400, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.gun.setFont(font)
        self.gun.setObjectName("gun")
        self.kupon_id_label_4 = QtWidgets.QLabel(Widget)
        self.kupon_id_label_4.setGeometry(QtCore.QRect(320, 230, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kupon_id_label_4.setFont(font)
        self.kupon_id_label_4.setObjectName("kupon_id_label_4")
        self.line_5 = QtWidgets.QFrame(Widget)
        self.line_5.setGeometry(QtCore.QRect(540, 70, 20, 391))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.kupon_id_label_5 = QtWidgets.QLabel(Widget)
        self.kupon_id_label_5.setGeometry(QtCore.QRect(280, 10, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kupon_id_label_5.setFont(font)
        self.kupon_id_label_5.setObjectName("kupon_id_label_5")
        self.line_3 = QtWidgets.QFrame(Widget)
        self.line_3.setGeometry(QtCore.QRect(0, 0, 761, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_7 = QtWidgets.QFrame(Widget)
        self.line_7.setGeometry(QtCore.QRect(260, 220, 291, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(Widget)
        self.line_8.setGeometry(QtCore.QRect(0, 220, 291, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(Widget)
        self.line_9.setGeometry(QtCore.QRect(0, 450, 761, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(Widget)
        self.line_10.setGeometry(QtCore.QRect(0, 340, 551, 20))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.termin_suresi = QtWidgets.QLineEdit(Widget)
        self.termin_suresi.setGeometry(QtCore.QRect(350, 280, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.termin_suresi.setFont(font)
        self.termin_suresi.setObjectName("termin_suresi")
        self.kupon_id_label_6 = QtWidgets.QLabel(Widget)
        self.kupon_id_label_6.setGeometry(QtCore.QRect(280, 350, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kupon_id_label_6.setFont(font)
        self.kupon_id_label_6.setObjectName("kupon_id_label_6")
        self.kupon_id_label_7 = QtWidgets.QLabel(Widget)
        self.kupon_id_label_7.setGeometry(QtCore.QRect(600, 220, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kupon_id_label_7.setFont(font)
        self.kupon_id_label_7.setObjectName("kupon_id_label_7")
        self.indirim = QtWidgets.QLineEdit(Widget)
        self.indirim.setGeometry(QtCore.QRect(600, 280, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.indirim.setFont(font)
        self.indirim.setObjectName("indirim")
        self.line_11 = QtWidgets.QFrame(Widget)
        self.line_11.setGeometry(QtCore.QRect(520, 220, 241, 20))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(Widget)
        self.line_12.setGeometry(QtCore.QRect(540, 340, 221, 20))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.kupon_id_label_8 = QtWidgets.QLabel(Widget)
        self.kupon_id_label_8.setGeometry(QtCore.QRect(30, 230, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kupon_id_label_8.setFont(font)
        self.kupon_id_label_8.setObjectName("kupon_id_label_8")
        self.teslimatsablon = QtWidgets.QLineEdit(Widget)
        self.teslimatsablon.setGeometry(QtCore.QRect(30, 290, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.teslimatsablon.setFont(font)
        self.teslimatsablon.setObjectName("teslimatsablon")
        self.kupon_id_label_9 = QtWidgets.QLabel(Widget)
        self.kupon_id_label_9.setGeometry(QtCore.QRect(40, 350, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kupon_id_label_9.setFont(font)
        self.kupon_id_label_9.setObjectName("kupon_id_label_9")
        self.urunonay = QtWidgets.QLineEdit(Widget)
        self.urunonay.setGeometry(QtCore.QRect(70, 400, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.urunonay.setFont(font)
        self.urunonay.setObjectName("urunonay")
        self.tl = QtWidgets.QCheckBox(Widget)
        self.tl.setGeometry(QtCore.QRect(570, 130, 121, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tl.setFont(font)
        self.tl.setChecked(False)
        self.tl.setObjectName("tl")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.baslat.setText(_translate("Widget", "Güncelle"))
        self.katsayi.setText(_translate("Widget", "1.85"))
        self.dosya_yukle_label.setText(_translate("Widget", "Dosya Yüklenmedi"))
        self.kupon_id_label.setText(_translate("Widget", "Bilgilendirme"))
        self.dosya_yukle.setText(_translate("Widget", "Dosya Yukle"))
        self.kupon_id_label_3.setText(_translate("Widget", "Katsayı"))
        self.usd.setText(_translate("Widget", "USD"))
        self.xml.setText(_translate("Widget", "XML"))
        self.kapat.setText(_translate("Widget", "İşlem Bitince Kapat"))
        self.gun.setText(_translate("Widget", "6"))
        self.kupon_id_label_4.setText(_translate("Widget", "Termin Süresi"))
        self.kupon_id_label_5.setText(_translate("Widget", "AMAZON N11 GETTER"))
        self.termin_suresi.setText(_translate("Widget", "10"))
        self.kupon_id_label_6.setText(_translate("Widget", "Kargo Kontrol Süresi"))
        self.kupon_id_label_7.setText(_translate("Widget", "İndirim"))
        self.indirim.setText(_translate("Widget", "20.00"))
        self.kupon_id_label_8.setText(_translate("Widget", "Teslimat Şablonu"))
        self.teslimatsablon.setText(_translate("Widget", "BONUSTİCARET"))
        self.kupon_id_label_9.setText(_translate("Widget", "Ürün Onayı"))
        self.urunonay.setText(_translate("Widget", "1"))
        self.tl.setText(_translate("Widget", "TL"))

